databases: 
  - name: pgpostgres
    ipAllowList: []

services:
  - type: web
    name: park-guide
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: bundle exec rails s
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: pgpostgres
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false

